before_script:
build:
  only:
   - production
  script:
   - cd /opt/ci_www/imread
   - git checkout .
   - git pull origin master   
   - rm -rf public/p
   - mkdir public/p
   - webpack -p
   - scp -r /opt/ci_www/imread/public/p ebook_manager@182.92.184.171:/opt/imread_new/public
   - scp -r /opt/ci_www/imread/src ebook_manager@182.92.184.171:/opt/imread_new/v3
   - ssh -t -t ebook_manager@182.92.184.171 "cd /opt/imread_new;python publish_real_cdn_file.py 'http://m.imread.com/';python publish_real_cdn_file.py 'http://m.imread.com/p/bundle1.js'"