before_script:
build:
  script:
   - cd /opt/ci_www/imread
   - git pull origin master
   - rm -rf p
   - mkdir p
   - mkdir p/src
   - cp -r src/img p/src/img
   - webpack -p
   - ssh -t -t ebook_manager@182.92.184.171 "cd /opt/imread_new;rm -rf tmp src;"
   - scp -r /opt/ci_www/imread/p/* ebook_manager@182.92.184.171:/opt/imread_new
   - ssh -t -t ebook_manager@182.92.184.171 "cd /opt/imread_new;python publish_real_cdn_dir.py   'http://m.imread.com/'"
only:
   - master